apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-03-05T05:53:00Z"
  generation: 1
  managedFields:
  - apiVersion: networking.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:egress: {}
        f:ingress: {}
        f:policyTypes: {}
    manager: HashiCorp
    operation: Update
    time: "2021-03-05T05:53:00Z"
  name: default-network-policy
  namespace: iss-ftp-nonp
  resourceVersion: "144385"
  selfLink: /apis/networking.k8s.io/v1/namespaces/iss-ftp-nonp/networkpolicies/default-network-policy
  uid: dc6fcce4-d32f-4b22-b347-c92ff5d33144
spec:
  egress:
  - to:
    - namespaceSelector:
        matchExpressions:
        - key: name
          operator: In
          values:
          - aks-periscope
          - azure-arc
          - gatekeeper-system
          - kube-system
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    to:
    - ipBlock:
        cidr: 10.200.0.10/32
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    to:
    - ipBlock:
        cidr: 10.202.0.10/32
  ingress:
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: name
          operator: In
          values:
          - aks-periscope
          - azure-arc
          - gatekeeper-system
          - kube-system
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress