apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-dns
  namespace: bb-datafactory
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - namespaceSelector:
            matchExpressions:
              - key: name
                operator: In
                values:
                  - aks-periscope
                  - azure-arc
                  - gatekeeper-system
                  - kube-system
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
